name: ascent_models
description: A starting point for Dart libraries or applications.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  ascent_utils: 0.1.0

dev_dependencies:
  dart_style: ^2.3.2
  lints: ^2.0.0
  test: ^1.21.0
